# application.yml
spring:
  output:
    ansi:
      enabled: always
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"
  level:
    root: INFO
    web: DEBUG
    "[org.springframework.security]": TRACE
    "[org.mklinkj.qna]": DEBUG
