DROP TABLE IF EXISTS t_employee CASCADE;

CREATE TABLE IF NOT EXISTS t_employee (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name          VARCHAR(255),
    location      VARCHAR(255),
    register_date DATE
);